In [2]:
s= 'Python'
a=list(s)
print(a)

['P', 'y', 't', 'h', 'o', 'n']


In [3]:
print(a[:3])

['P', 'y', 't']


In [5]:
s='12\\34'
print(s)

12\34


In [6]:
a ='this is the first half'
b= 'and this is the second half'

a+b

'this is the first halfand this is the second half'

In [8]:
template ='{0:.2f} {1:s} are worth US${2:d}' #앞의 인덱스 숫자는 생략가능, 그리고 한꺼번에 붙여서도 가능

template.format(4.5560,'Argentine pesos',1)

'4.56 Argentine pesos are worth US$1'

In [10]:
total=0
for i in range(10001):
    total +=i

print(total)

50005000


In [11]:
values=1,2,3,4,5
print(type(values))

<class 'tuple'>


In [16]:
a,b,*rest=values
print(a,b)
print(*rest)
print(type(rest))
print(type(a))

1 2
3 4 5
<class 'list'>
<class 'int'>


In [20]:
a,b #튜플

(7, 8)

In [33]:
list1=[(1,2,3),(4,5,6),(7,8,9)]

for a,b,c in list1:
    print(a)

1
4
7


In [32]:
seq1=['one','two','three']
seq2=['foo','bar','baz']

zipped=zip(seq1,seq2)

del list
print(list(zipped))

[('one', 'foo'), ('two', 'bar'), ('three', 'baz')]


In [35]:
for i,(a,b) in enumerate(zip(seq1,seq2)):
    print(i+1,a,b)

1 one foo
2 two bar
3 three baz


In [36]:
mapping=dict(zip(range(5),reversed(range(5))))

mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [41]:
strings =['a','as','bat','car','dove','python']
re_strings=[]
for each in reversed(strings):
    re_strings.append(each.upper())

print(re_strings)




['PYTHON', 'DOVE', 'CAR', 'BAT', 'AS', 'A']


In [42]:
import numpy as np

my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [43]:
%time for _ in range(10): my_arr2=my_arr*2

Wall time: 30 ms


In [44]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 2.61 s


In [86]:
import numpy as np

data = np.random.randn(2, 3)

print(data)

print(data.shape)
print(data.dtype)


[[ 0.01471288  0.72271059 -0.49782565]
 [ 0.97590313 -0.02853851 -0.08307507]]
(2, 3)
float64


In [87]:
data1=[6,7.5,8,0,1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])