In [ ]:
# NumPy(배열 데이터를 효과적으로 다루는 패키지)

# 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지.
#  파이썬 기본 데이터 형식과 내장 함수를 이용하는 것보다 효과적으로 처리할 수 있다.

In [2]:
#배열 생성

import numpy as np


# 배열이란 순서가 있는 같은 종류의 데이터가 저장된 집합. numpy를 이용해서 배열을 처리하려면 먼저 numpy배열을 생성해야 한다.


data1 = [0,1,2,3,4,5]

a1= np.array(data1)
a1

# 리스트 데이터를 numpy의 array() 로 넣어서 정수만으로 구성된 numpy배열을 만들었다.


array([0, 1, 2, 3, 4, 5])

In [4]:
data2=[0,1,5,4,12,0.5]

a2 = np.array(data2)
a2

#출력 결과를 보면 입력된 원래 리스트와 차이가 보인다 . 이것은 같은 종류의 데이터만
#저장할 수 있는 배열의 특징으로 혼합이 되어 있을 때는 모두 실수로 변환하기 때문이다.

array([ 0. ,  1. ,  5. ,  4. , 12. ,  0.5])

In [7]:
print(a1.dtype)
print(a2.dtype)

# 데이터 타입을 보면 a1은 정수 int64비트 a2는 실수 float64비트이다.



int32
float64


In [8]:
np.array([0.5,2,0.01,8])

# 앞에서는 data1, data2를 먼저 리스트로 만들어 numpy배열로 변경하였으나 
# array에 직접 넣어서 배열 객체를 생성할 수 있다.


array([0.5 , 2.  , 0.01, 8.  ])

In [9]:
# 2차원 배열..
np.array([ [1,2,3],[4,5,6],[7,8,9]                            ])



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# 범윌을 지정해서 배열을 생성

np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
b1=np.arange(12).reshape(4,3)

b1
# 주의할 점은 arange() 생성되는 원소 개수와 reshape(m,n) m*n의 수가 맞아야만 한다.



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b2 =np.arange(5)
b2.shape

(5,)

In [19]:
# 범위의 시작과 끝을 지정하고 개수를 지정해서 배열을 생성하는 linspace()

np.linspace(1,10,10)

# start,stop,number



array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(1,10)

#갯수를 생략하면 50으로 간주한다.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [22]:
#특별한 형태의 배열 생성...
# zeros() : 모든 원소가 0인 다차원 배열을 생성 
# ones() : 모든 원소가 1인 다차원 배열을 생성

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# 단위 행렬 ... n*n인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# numpy의 배열은 숫자 만이 아니라 문자열도 원소로 다룰 수 있다.

np.array(['0.5','2','0.01','3.141592','3.1415654654654'])

# dtype='<u8'의 의미는 데이터 형식이 유니코드 문자의 수가 최대 8개라는 것을 의미한다.

# 배열이 문자열로 돼있으면 연산을 위해서는 숫자(정수/실수)로 변환해야 한다.

array(['0.5', '2', '0.01', '3.141592', '3.1415654654654'], dtype='<U15')

In [30]:
a = np.array(['0.5','2','0.01','3.141592','3.141592'])
numa=a.astype(float)
numa

array([0.5     , 2.      , 0.01    , 3.141592, 3.141592])

In [31]:
a.dtype


dtype('<U8')

In [32]:
numa.dtype

dtype('float64')

In [35]:
numi =numa.astype(int)
numi

array([0, 2, 0, 3, 3])

In [36]:
numi.dtype

dtype('int32')

In [4]:
# 난수로 배열을 만드는 또 다른 방법 

# rand() a,b 미만 사이의 실수 a는 포함이되고 b는 포함이 되지 않는다.

np.random.rand(2,3) #2행 3열 0에서 1미만의 실수로 난수로 배열 생성






array([[0.03701935, 0.12982503, 0.27676172],
       [0.3999235 , 0.43291946, 0.61818328]])

In [6]:
# randint()
b1=np.random.randint(1,46) #0부터 10미만으로 정수 1개 난수 생성
lotto=[]
for i in range(6):
    while b1 in lotto:
        b1=np.random.randint(1,46)
    lotto.append(b1)

lotto.sort()
print(lotto)

[5, 8, 10, 16, 34, 44]


In [7]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [303]:
import random
a= random.sample(range(1,46),6)
print(a)

[30, 38, 26, 3, 25, 9]


In [304]:
np.random.choice(range(1,46),6,replace=False)

array([24, 15, 33, 16,  8, 32])

In [307]:
# 배열의 선언...
# numpy 배열은 다양하게 연산을 할 수 있다. 배열의 형태가 같다면 m*n +,-,*,/ 가능하다.

arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])

#배열의 형태가 같은 두 개의 1차원 배열 생성...ndarray.shape 결과가 같다는 말과 같다.

# 두 배열의 합은 각 배열의 같은 위치의 원소끼리 더한다.

arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2


array([10., 10., 10., 10.])

In [308]:
#복합 연산

arr1/(arr2 **2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [309]:
#배열은 비교연산도 가능하다. 원소별로 조건과 일치하는지 검사

arr1>20

array([False, False,  True,  True])

In [310]:
# 통계를 위한 연산

# Numpy dpsms 배열의 합sum 평균mean 편차std 분산var 최소값min 최대값max 누적합cumsum..

arr3= np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [311]:
arr3.sum()

10

In [312]:
arr3.mean()

2.0

In [313]:
arr3.std()

1.4142135623730951

In [314]:
arr3.var()

2.0

In [315]:
[arr3.min(), arr3.max()]

[0, 4]

In [316]:
arr3.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [317]:
arr3

array([0, 1, 2, 3, 4])

In [ ]:
# 행렬 연산 - 배열의 단순 연산 뿐만아니라 선형대수(Linear algebra)를 위한 행렬 연산도 지원한다.

In [ ]:
# 배열의 인덱싱 - 배열을 다루다 보면 원소를 이용할 때가 많다.
#                   numpy에서는 배열의 위치, 조건, 범위를 지정해 원소를 선택할 수 있다.
#                   배열의 위치나 조건을 지정해서 원소를 선택하는 것을 인덱싱이라고 한다
#                   범위를 지정해 배열의 원소들을 선택하는 것을 슬라이싱이라고 한다.



In [318]:
a1 =np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [319]:
a1[1]

10

In [322]:
a1[[1,3,4]]

array([10, 30, 40])

In [324]:
# 2차원 배열에서의 인덱싱

a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [325]:
a2[0][2]

30

In [326]:
a2[0,2]

30

In [328]:
a2[2,2]=99
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 99]])

In [329]:
a2[1]

array([40, 50, 60])

In [330]:
a2[1]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 99]])

In [331]:
# 2차원 배열에서 여러 원소 선택

a2[[0,2],[0,1]]

array([10, 80])

In [332]:
a = np.array([1,2,3,4,5,6])

a[a>3]

array([4, 5, 6])

In [333]:
a = np.array([1,2,3,4,5,6])

a[a%2==0]

array([2, 4, 6])

In [335]:
# 배열의 슬라이싱...

# 인덱싱은 원소 하나씩 선택하여 처리하는 방식인 반면에 슬라이싱은 여러개의 원소를 다룬다.


b=np.array([0,1,2,3,4,5])

b[1:4]

array([1, 2, 3])

In [336]:
b[2:]

array([2, 3, 4, 5])

In [337]:
b[2:5]=[20,30,40]

In [338]:
b

array([ 0,  1, 20, 30, 40,  5])

In [339]:
b[:]=0
b

array([0, 0, 0, 0, 0, 0])

In [351]:

c = np.arange(10,100,10).reshape(3,3)
c

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [353]:
c[1:3,1:3]   # 행시작:행끝, 열시작:열끝


#Numpy 를 이용해서 배열을 효율적으로 처리하는 방법들을 배웠다.
# 우리가 앞으로 분석할 데이터의 대부분이 배열 형태로 이루어져 있다.
# 따라서 numpy를 잘 익히면 좀 더 편리하고 효율적으로 처리할 수 있다.

array([[50, 60],
       [80, 90]])

In [ ]:
#pandas
# 대량의 데이터 분석과 처리를 쉽게 할 수 있도록 도와주는 패키지이다.
# pandas는 numpy를 기반으로 만들어졌으나 좀더 복잡한 데이터 분석에 특화되어 있다.
# numpy는 같은 데이터 타입의 배열만 처리할 수 있으나, 
# pandas는 타입이 섞여 있어도 처리할 수 있다. pandas에는 아주아주 많은 기능들이 있다.
# 여기서는 기본적인 활용법을 살펴보자.

In [10]:
# Series
import pandas as pd

# 판다스에서 데이터를 생성하는 가장 기본적인 방법 Series()를 이용하는 것이다.
# Series형의 1차원 데이터

s1 = pd.Series([10,20,30,40,50])
s1


# 결과로 볼 수 있듯이 Series를 출력하면 데이터 앞에 index가 함께 표시된다.
# Series 생성 시 자동으로 만들어진 것으로 데이터를 처리할 때 이용하게 된다.

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [357]:
#Series데이터는 index와 values로 분리할 수 있다.

s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [358]:
s1.index

# index는 범위로 표시된다.

RangeIndex(start=0, stop=5, step=1)

Numpy의 경우에는 배열의 모든 원소가 데이터 타입이 같아야 했지만
pandas는 원소들의 데이터 타입이 달라도 된다.

In [360]:
s2= pd.Series(['a','b','c',1,2,3])

s2

# Series()로 데이터를 생성할 때는 문자와 숫자가 혼합된 리스트를 인자로 이용할 수 있다.

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [361]:
# 데이터가 없을 때는 np.nan 으로 데이터가 없다고 표시한다.

s3= pd.Series([np.nan,10,30])
s3

#NaN은 데이터가 없다는 것을 의미한다. 즉 index는 있지만 실제 값은 없다.

0     NaN
1    10.0
2    30.0
dtype: float64

In [362]:
# 인자로 index를 명시적으로 입력하면 index에는 자동으로 생성되는 index대신에 원하는 
# 값을 인덱스로 설정할 수 있다.

index=['2021-09-27','2021-09-28','2021-09-29','2021-09-30']

s4 = pd.Series([200,190,np.nan,205], index=index)

s4

2021-09-27    200.0
2021-09-28    190.0
2021-09-29      NaN
2021-09-30    205.0
dtype: float64

In [363]:
# 딕셔너리를 이용하면 좀 더 편하게 만들 수 있다.

s5=pd.Series({'국어':100,'영어':98,'수학':100})

s5

국어    100
영어     98
수학    100
dtype: int64

In [367]:
# 날짜 자동 생성

# 위에서는 index에 날짜를 하나씩 전부 입력했다. 날짜가 많다면 입력하기 쉽지 않다.

# pandas의 date_range()를 사용하면 원하는 날짜를 자동으로 생성한다.

pd.date_range(start='2021-09-27',end='2021-09-30')

#시작부터 하루씩 증가한 날짜 데이터가 생성되었다.
# 또한 날짜는 다양한 형태로 표현할 수 있다.
# 다양한 형태로 입력을 할 수는 있지만 생성된 날짜 형식은 모두 동일하다.

DatetimeIndex(['2021-09-27', '2021-09-28', '2021-09-29', '2021-09-30'], dtype='datetime64[ns]', freq='D')

In [368]:
pd.date_range(start='2021/09/27',end='2021/09/30')

DatetimeIndex(['2021-09-27', '2021-09-28', '2021-09-29', '2021-09-30'], dtype='datetime64[ns]', freq='D')

In [369]:
pd.date_range(start='2021/09/27',periods=7)

DatetimeIndex(['2021-09-27', '2021-09-28', '2021-09-29', '2021-09-30',
               '2021-10-01', '2021-10-02', '2021-10-03'],
              dtype='datetime64[ns]', freq='D')

In [371]:
pd.date_range(start='2019/01/01',periods=4,freq='2D')

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07'], dtype='datetime64[ns]', freq='2D')

In [379]:


pd.date_range(start='2019/01/01',periods=12,freq='2M',tz='Asia/Seoul')

DatetimeIndex(['2019-01-31 00:00:00+09:00', '2019-03-31 00:00:00+09:00',
               '2019-05-31 00:00:00+09:00', '2019-07-31 00:00:00+09:00',
               '2019-09-30 00:00:00+09:00', '2019-11-30 00:00:00+09:00',
               '2020-01-31 00:00:00+09:00', '2020-03-31 00:00:00+09:00',
               '2020-05-31 00:00:00+09:00', '2020-07-31 00:00:00+09:00',
               '2020-09-30 00:00:00+09:00', '2020-11-30 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='2M')

In [381]:
pd.date_range(start='2019/01/01',periods=12,freq='2BM')

DatetimeIndex(['2019-01-31', '2019-03-29', '2019-05-31', '2019-07-31',
               '2019-09-30', '2019-11-29', '2020-01-31', '2020-03-31',
               '2020-05-29', '2020-07-31', '2020-09-30', '2020-11-30'],
              dtype='datetime64[ns]', freq='2BM')

D 하루주기
W 한주주기
M 월말 날짜..
BM 업무 월말 날짜
MS 월초 날짜
BMS 업무 월초 날짜
Q 분기 끝날짜
BQ 업무일 분기 끝날짜
QS 분기 시작
BQS 업무 분기 시작
A 일년 끝날짜기준 주기
AS 일년 시작 날짜 기준 주기

In [383]:
pd.date_range(start='2021/09/27 09:00', periods=9,freq='BH')

DatetimeIndex(['2021-09-27 09:00:00', '2021-09-27 10:00:00',
               '2021-09-27 11:00:00', '2021-09-27 12:00:00',
               '2021-09-27 13:00:00', '2021-09-27 14:00:00',
               '2021-09-27 15:00:00', '2021-09-27 16:00:00',
               '2021-09-28 09:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [384]:
pd.date_range(start='2021/09/27 09:00', periods=9,freq='30T')

DatetimeIndex(['2021-09-27 09:00:00', '2021-09-27 09:30:00',
               '2021-09-27 10:00:00', '2021-09-27 10:30:00',
               '2021-09-27 11:00:00', '2021-09-27 11:30:00',
               '2021-09-27 12:00:00', '2021-09-27 12:30:00',
               '2021-09-27 13:00:00'],
              dtype='datetime64[ns]', freq='30T')

In [385]:
# DataFrame - 표와 같은 라벨이 있는 2차원 데이터를 생성하고 처리한다.
#           거의 모든 데이터 형을 저장할 수 있다. numpy 배열과 Series도
#           넣을 수 있다. 가로축을 index라고 하고 세로축을 column
#           index, column 자동생성



pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [386]:
data= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index=pd.date_range('2021/09/27',periods=4)
columns=['A','B','C']
pd.DataFrame(data,index=index,columns=columns)

# 출력 결과에서 index와 columns에 지정한 값들이 들어간 것을 볼 수 있다.

A   B   C
2021-09-27   1   2   3
2021-09-28   4   5   6
2021-09-29   7   8   9
2021-09-30  10  11  12

In [388]:
data ={'연도':[2015,2016,2017,2018,2019,2020],'지사':['한국','중국','일본','태국','영국','미국'],'고객수':[200,250,450,300,500,600]}

data

{'연도': [2015, 2016, 2017, 2018, 2019, 2020],
 '지사': ['한국', '중국', '일본', '태국', '영국', '미국'],
 '고객수': [200, 250, 450, 300, 500, 600]}

In [389]:
pd.DataFrame(data)

# index는 자동으로 생성이 되었고 딕셔너리의 키값이 columns에 들어감
# 자세히 살펴보면 열은 입력한 순서대로 생성되지 않을 수도 있다.
# 순서까지 지정하려면 columns = [컬럼명]을 이용해서 순서까지 지정한다.

연도  지사  고객수
0  2015  한국  200
1  2016  중국  250
2  2017  일본  450
3  2018  태국  300
4  2019  영국  500
5  2020  미국  600

In [390]:
pd.DataFrame(data, columns=['지사','고객수','연도'])

지사  고객수    연도
0  한국  200  2015
1  중국  250  2016
2  일본  450  2017
3  태국  300  2018
4  영국  500  2019
5  미국  600  2020

In [393]:
# dataframe에서 index, columns, value는 각각 dataframe_data.index, dataframe_data.columns, dataframe_values.index 로 확인한다.

df=pd.DataFrame(data, columns=['지사','고객수','연도'])

df.index
df.columns
df.values

array([['한국', 200, 2015],
       ['중국', 250, 2016],
       ['일본', 450, 2017],
       ['태국', 300, 2018],
       ['영국', 500, 2019],
       ['미국', 600, 2020]], dtype=object)

In [395]:
# 데이터 연산

#pandas의 series()와 pandas의 dataframe으로 생성한 데이터 끼리는 사칙 연산을 할 수 있다.
s1=pd.Series([1,2,3,4,5])
s2= pd.Series([10,20,40,50])

s1 +s2

0    11.0
1    22.0
2    43.0
3    54.0
4     NaN
dtype: float64

In [ ]:
#파이선의 리스트와 넘파이의 배열과는 다르게
# pandas의 데이터끼리는 서로 크기가 달라고 연산을 할 수 있다
# 이경우 연산을 할 수 있는 항목들만 연산을 수행한다. 업으면 nan표시

In [12]:
t1={'A':[1,2,3,4,5],'B':[100,200,300,400,500]} 
df1=pd.DataFrame(t1)
t2={'A':[1,2,3,4],'B':[100,200,300,400]} 
df2=pd.DataFrame(t2)

In [399]:
df1+df2

A      B
0  2.0  200.0
1  4.0  400.0
2  6.0  600.0
3  8.0  800.0
4  NaN    NaN

pandas데이터 통계 분석

In [13]:
t3={'봄':[1,2,3,4,5],'여름':[5,6,7,8,9],'가을':[4,5,6,7,8],'겨울':[2,3,4,5,6]}

index=['2021','2022','2023','2024','2025']

df3=pd.DataFrame(t3,index=index)

In [14]:
df3.mean()
#계절별 평균

봄     3.0
여름    7.0
가을    6.0
겨울    4.0
dtype: float64

In [406]:
df3.std()
#계절별 표준편차

봄     1.581139
여름    1.581139
가을    1.581139
겨울    1.581139
dtype: float64

In [407]:
df3.mean(axis=1) # 0기본, 열별로, 1 = 행별로

2021    3.0
2022    4.0
2023    5.0
2024    6.0
2025    7.0
dtype: float64

In [408]:
df3.describe()

봄        여름        가을        겨울
count  5.000000  5.000000  5.000000  5.000000
mean   3.000000  7.000000  6.000000  4.000000
std    1.581139  1.581139  1.581139  1.581139
min    1.000000  5.000000  4.000000  2.000000
25%    2.000000  6.000000  5.000000  3.000000
50%    3.000000  7.000000  6.000000  4.000000
75%    4.000000  8.000000  7.000000  5.000000
max    5.000000  9.000000  8.000000  6.000000

# 대량의 데이터가 입력된 데이터프레임에서 원하는 데이터만
# 선택하는 것은 데이터를 분석할 때 꼭 필요하다.
# 원본 훼손 없이 원하는 부분만 선택하는 방법들을 살펴보자


In [409]:
scores= pd.read_excel('학생시험성적.xlsx')
scores

학생  국어  영어  수학         평균
0  A  80  90  85  85.000000
1  B  90  95  95  93.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333
4  E  75  90  85  83.333333